version: '3.8'

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/express-db
      - JWT_SECRET=itsRandom123stringtoguessthepassword
      - CLOUDINARY_CLOUD_NAME=ddyn5lbds
      - CLOUDINARY_API_KEY=897941549959919
      - CLOUDINARY_API_SECRET=VSxUagxVPDyQnZa9Wtb2K21V04o
      - CLOUDINARY_URL=cloudinary://897941549959919:VSxUagxVPDyQnZa9Wtb2K21V04o@ddyn5lbds
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
